spring:
  main:
    web-application-type: none
    banner-mode: "off"
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    url: jdbc:postgresql://${spring.datasource.host}:5432/test-db
    username: test
    password: test@123
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      idle-timeout: 30000
      pool-name: SpringBootHikariCP
      minimum-idle: 3
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      auto-commit: true
  jpa:
    hibernate.ddl-auto: create
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        connection:
          isolation: 2
    open-in-view: false
  sql:
    init:
      mode: always
logging:
  level:
    root: info
#    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.springframework.orm.jpa: DEBUG
#    org.hibernate.event.internal: TRACE
#    org.hibernate.internal.SessionImpl: TRACE